Feat: Добавлена DB, реализован функционал Booking
missfury/java-shareit pull request #3
Opened 2023-08-03 16:46 UTC by missfury

2023-08-03 23:06 UTC, NikolaiDem requested changes

2023-08-03 23:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +
Еще лучше проверить, что вещь не забронирована никем другим на запрашиваемые даты.

2023-08-03 23:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotAvailableException("Бронирование предмета с id= " + bookingId + " еще не подтверждено");
Наверное, "уже подтверждено"

2023-08-03 23:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStatus().equals(Status.APPROVED)) {
А если статус равен Rejected?

2023-08-03 23:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/exception/handler/ErrorHandler.java
> +        log.debug("Not found error: {}", e.getMessage());
Больше похоже на log.error(...)

2023-08-03 23:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToOne
У одного юзера может быть несколько предметов

2023-08-03 23:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    @ResponseBody
Аннотация лишняя, RestController уже учитывает формат ответа

2023-08-07 17:05 UTC, missfury commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStatus().equals(Status.APPROVED)) {
Хороший вопрос. Но в ТЗ не оговорено, как должно вести себя приложение в этом случае - то ли "напомнить" исключением, что отказ уже был, то ли дать возможность "передумать" и изменить статус.

2023-08-07 20:17 UTC, NikolaiDem approved these changes

2023-08-07 20:45 UTC, merged