feat: Реализован функционал Request, добавлены тесты.
missfury/java-shareit pull request #4
Opened 2023-08-20 06:32 UTC by missfury

2023-08-20 19:54 UTC, NikolaiDem requested changes

2023-08-20 19:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    List<BookingDto> getAllBookingByState(Long id, String state, int from, int size);
Лучше добавить Pageable вместо from и size

2023-08-20 19:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public ItemDto(Long id, String name, String description, Boolean available) {
Вместо шаблонного кода лучше использовать lombok

2023-08-20 19:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestMapper.java
> +                .requesterId(itemRequest.getRequester().getId() != null ? itemRequest.getRequester().getId() : null)
В такой проверке itemRequest.getRequester().getId() != null смысла нет. 
Это равноценно                 .requesterId(itemRequest.getRequester().getId())

2023-08-20 19:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +    List<ItemRequestDto> getAllRequests(Long id, int from, int size);
Лучше использовать Pageable вместо from и size

2023-08-20 19:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/util/Pagination.java
> +    public static Pageable getPageOrThrow(Integer from, Integer size) {
Почему для ItemController-а формирование PageRequest происходит в отдельной утилите в отличие от других контроллеров?

2023-08-20 19:54 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private BookingServiceImpl bookingService;
Можно BookingService
И для BookingServiceTest, ItemServiceTest, ItemRequestServiceTest

2023-08-20 19:54 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +    @MockBean
Использование моков для интеграционных тестов не предполагается

2023-08-20 23:29 UTC, missfury commented on src/main/java/ru/practicum/shareit/util/Pagination.java
> +    public static Pageable getPageOrThrow(Integer from, Integer size) {
При аналогичной другим контроллерам реализации здесь отчего-то начали падать тесты в постмане. И кто-то (я) не придумал ничего лучше, чем сделать всю паджинацию разношерстной. Конечно же, дело не в реализации было, а скорее в незамеченной ошибке, помноженной на состояние "затупил", а потом еще и в нежелании трогать то, что хоть как-то, а работает. Но идея вынести это в утилиту мне кажется здравой - страницы формируются везде идентично, а сортировку, где она нужна, можно и кастомно добавить.

2023-08-21 01:18 UTC, missfury commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private BookingServiceImpl bookingService;
Для BookingServiceTest, ItemServiceTest, ItemRequestServiceTest нельзя, там @InjectMocks, который не работает с интерфейсами

2023-08-21 19:59 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private BookingServiceImpl bookingService;
Точно)

2023-08-22 06:11 UTC, merged